"""Minimal PDF report writer (Plan2 v2.0) — pure stdlib.

Writes a compact, standards-compliant PDF with one line per alive host.
Fonts: only ``Courier`` (built into every PDF viewer), encoding: WinAnsi.

This is intentionally dependency-free; if you need rich layouts, export
HTML (``--export html``) and print-to-PDF from your browser.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from netsight.models import ScanResult

if TYPE_CHECKING:
    pass

_PDF_HEADER = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"  # binary marker


def _escape(text: str) -> str:
    """Escape PDF string special characters."""
    return (text.replace("\\", "\\\\").replace("(", "\\(")
            .replace(")", "\\)"))


def _pdf_stream(lines: list[str]) -> bytes:
    """Generate the raw PDF content stream from a list of text lines."""
    y = 780
    parts: list[bytes] = []
    for line in lines:
        parts.append(
            f"BT /F1 9 Tf 40 {y} Td ({_escape(line)}) Tj ET\n".encode("latin-1", "replace")
        )
        y -= 12
        if y < 40:  # Prevent overflow; reports are meant to fit on one page.
            break
    return b"".join(parts)


def export_pdf(
    scan: ScanResult,
    directory: str | Path | None = None,
    filename: str | None = None,
) -> Path:
    """Write a scan result to a PDF file.

    Args:
        scan: The completed scan result.
        directory: Output directory (defaults to ./exports).
        filename: Override filename.

    Returns:
        Path to the written ``.pdf`` file.
    """
    from netsight import __version__

    out_dir = Path(directory) if directory else Path.cwd() / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)
    from netsight.exporter import _timestamp_slug
    name = filename or f"netsight_scan_{_timestamp_slug()}.pdf"
    path = out_dir / name

    # ---- Build the text = -----------------------------------------------------
    lines: list[str] = [
        "NetSight Scan Report",
        "====================",
        "",
        f"Target subnet      : {scan.subnet}",
        f"Started            : {scan.started_at}",
        f"Finished           : {scan.finished_at or '—'}",
        f"Duration           : {scan.duration_s:.1f}s",
        f"Hosts discovered   : {len(scan.alive_hosts)}",
        f"Open ports found   : {scan.open_port_count}",
        "",
        "IP                Hostname         MAC                Vendor           OS         RTT(ms)  Ports",
        "----------------  ---------------  -----------------  ---------------  ---------  -------  -----",
    ]
    for host in scan.alive_hosts:
        ports = ",".join(str(p["port"]) for p in host.open_ports) or "-"
        lines.append(
            f"{host.ip:<18}{host.hostname:<17}{host.mac:<19}{host.vendor:<17}"
            f"{host.os_guess:<11}{f'{host.response_ms or 0:.0f}':>8}  {ports}"
        )

    lines += ["", f"Generated by NetSight v{__version__} — internal inventory only"]
    text_stream = _pdf_stream(lines)

    # ---- Assemble the PDF object graph --------------------------------------
    # Objects:
    #   1: Catalog
    #   2: Pages tree
    #   3: Page
    #   4: Content stream
    #   5: Font object
    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>")
    objects.append(
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>"
    )
    objects.append(
        b"<< /Length " + str(len(text_stream)).encode() +
        b" >>\nstream\n" + text_stream + b"\nendstream"
    )
    objects.append(
        b"<< /Type /Font /Subtype /Type1 /Name /F1 /BaseFont /Courier >>"
    )

    # xref table
    buffer = bytearray()
    buffer.extend(_PDF_HEADER)
    offsets: list[int] = []
    for i, obj in enumerate(objects, 1):
        offsets.append(len(buffer))
        buffer.extend(f"{i} 0 obj\n".encode())
        buffer.extend(obj + b"\n")
        buffer.extend(b"endobj\n")

    xref_pos = len(buffer)
    buffer.extend(b"xref\n")
    buffer.extend(f"0 {len(objects) + 1}\n".encode())
    buffer.extend(b"0000000000 65535 f \n")
    for off in offsets:
        buffer.extend(f"{off:010} 00000 n \n".encode())

    buffer.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n".encode()
    )

    with open(path, "wb") as fh:
        fh.write(bytes(buffer))
    return path
